// frontend/vue/src/views/Game.vue
<!-- author: Halva Jindřich (xhalva05) -->
<!-- brief: GameView component controls rendering the game board and handling the game logic -->

<template>
  <div id="page" style="width: 100%;justify-self: center;">

    <div class="title_container">
      <p class="title">MINESWEEPER</p>
      <router-link to="/"><button id="menu_btn">Menu<img class="img_btn" src="/menu.png" width="20" height="20"></button></router-link>
      <button id="reset_btn" @click="difficultyChange" >Reset<img class="img_btn" src="/reset.png" width="20" height="20"></button>
    </div>

    <div class="container game">
      <div id="board">
        <div>
          <div v-if="board?.status.isLost || board?.status.isWon">
            <p class="status_text">YOU</p>
          </div>
        </div>
        <div v-if="error">
            <p>Error: {{ error }}</p>
        </div>
        <div v-else-if="board" class="game_board">
          <div v-for="(row, rowIndex) in board.board" :key="rowIndex" class="board_row">
            <div v-for="(cell, cellIndex) in row" :key="cellIndex"
                 :class="{ [cellClass]: true, revealed: cell.isRevealed, flagged: cell.isFlagged, isMine: (cell.value === -1 && cell.isRevealed), nullCell: (cell.value === 0 && cell.isRevealed)}" 
                 class="board_cell" v-on:click.left="reveal_cell(rowIndex, cellIndex)" v-on:click.right="flag_cell(rowIndex, cellIndex)"
                 oncontextmenu="return false;">
              {{ cell.isRevealed ? ((cell.value === -1 || cell.value == 0) ? "" : cell.value) : "" }}
            </div>
          </div>
        </div>
        <div v-else>
          <p>Loading...</p>
        </div>

        <div>
          <div v-if="board?.status.isLost">
            <p class="status_text">LOST</p>
          </div>
          <div v-if="board?.status.isWon">
            <p class="status_text">WON</p>
          </div>
        </div>
      </div>

      <div id="hints">
        <div class="hint">
          <button id="eye_hint" v-on:click="HintReq('reveal')"><i class="fa-solid fa-eye"></i></button>
          <div id="eye_hint_text" style="font-size: small;">Reveal non-mine cell hint. 15 seconds will be added to time</div>
        </div>
        <div class="hint">
          <button id="flag_hint" v-on:click="HintReq('flag')"><i class="fas fa-flag"></i></button>
          <div id="flag_hint_text" style="font-size: small;">Flag mine hint. 15 seconds will be added to time</div>
        </div>
      </div>

      <div id="bottom_info">
        <div class="stats">
          Time: {{ time }} 
        </div>
        <div class="stats">
          Mines left: {{ minesLeft }}
        </div>
        <div class="stats">
          Difficulty: <form><select v-model="difficulty" @change="difficultyChange" id="diff_select">
                        <option value="easy">Easy</option>
                        <option value="medium">Medium</option>
                        <option value="hard">Hard</option>
                      </select></form>
        </div>
      </div>
    </div>

    <div id="chat_btn_div">
      <button id="chat_btn" v-on:click="openCloseChat()">Open chat <i class="fa-regular fa-comment-dots"></i></button>
    </div>
  </div>

  <div id="chat_div" :style="{ display: isChatOpen ? 'grid' : 'none' }">
    <button class="close_btn" v-on:click="openCloseChat()"><i class="fa-solid fa-xmark"></i></button>
    <h3>Welcome to the game chat!</h3>
    <div id="chat_text">
      <div v-for="(msg, index) in chat" :key="index" class="chat_msg">
          <b>{{msg.sender}}</b> : {{msg.content}}<br>
          <span style="color: rgb(255, 255, 255, 0.3);">{{ new Date(((( msg.timestamp.seconds) * 1000))).toUTCString() }}</span><br><br>
      </div>
    </div>
    <form id="chat_input" v-on:submit.prevent="sendChatMsg">
      <input type="text" v-model="newMsg" id="chat_input_text" placeholder="Type your message here...">
      <button type="submit" id="chat_send_btn">Send</button>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { GameBoard } from "@/../../shared/types/game";
import { getUser } from "@/http_requests/getUser";
import { format_time } from "@/lib/format-time";
import { count_mines_left } from "@/lib/count-mines-left";
import { changeDifficulty } from "@/http_requests/changeDifficulty";
import { revealCell } from "@/http_requests/revealCell";
import { flagCell } from "@/http_requests/flagCell";
import { sendTimeToBE } from "@/http_requests/sendTimeToBE";
import { hint } from "@/http_requests/hint";
import { getChatMsgs } from "@/http_requests/getChatMsgs";
import { sendChatMsg } from "@/http_requests/sendChatMsg";
 
export default defineComponent({
  name: "GameView",
  data() {
    return {
      board: null as GameBoard | null,
      nickname: getUser(),
      time: format_time(0),
      newMsg: "" as string,
      chat: [] as { id: string; content: string, timestamp: { seconds: number, nanoseconds: number }, sender: string }[],
      timer: null as number | null,
      difficulty: "medium",
      isChatOpen: false,
      error: null as string | null,
    };
  },
  computed: {
    //show the number of mines left on the board
    minesLeft(): number {
      return this.board ? count_mines_left(this.board) : 0;
    },
    //set the cell clas based on the difficulty
    cellClass(): string {
      return `board_cell_${this.difficulty}`;
    },
  },
  methods: {
    //start the timer
    initTimer(seconds: number = 0) {
      this.timer = setInterval(() => {
        seconds++;
        this.time = format_time(seconds);
      }, 1000);
    },
    //add 15 seconds to the timer (hint was used)
    add15Seconds(){
      var act_time = this.time.split(":");
      var act_seconds = parseInt(act_time[0]) * 60 + parseInt(act_time[1]);
      act_seconds += 15;
      clearInterval(this.timer!);
      this.time = format_time(act_seconds);
      this.initTimer(act_seconds);
    },
    //change the difficulty of the game
    async difficultyChange() {
      clearInterval(this.timer!);
      this.time = format_time(0);
      this.initTimer();
      try {
        changeDifficulty(this.difficulty).then((newBoard) => {
          this.board = newBoard;
        });
      }
      catch (err) {
        this.error = (err as Error).message;
      }
    },
    //reveal the cell on the board after left click
    async reveal_cell(row: number, col: number) {
      console.log("reveal cell");
      if (this.board) {
        this.board = await revealCell(row, col);
        if(this.board.status.isLost || this.board.status.isWon){
          //stop the timer if the game is over
          clearInterval(this.timer!);
          if(this.board.status.isWon){
            this.actualizeLeaderboard();
          }
        }
      }
    },
    //flag the cell on the board after right click
    async flag_cell(row: number, col: number) {
      console.log("flag cell");
      if (this.board) {
        //check if the game is not over
        if(this.board.status.isLost || this.board.status.isWon){
          clearInterval(this.timer!);
          if(this.board.status.isWon){
            this.actualizeLeaderboard();
          }
        }
        this.board = await flagCell(row, col);
      }
    },
    //send the time to the backend to actualize the leaderboard
    async actualizeLeaderboard() {
      try{
        var act_time = this.time.split(":");
        var act_seconds = parseInt(act_time[0]) * 60 + parseInt(act_time[1]);
        sendTimeToBE(act_seconds, this.difficulty);
      }
      catch (err) {
        this.error = (err as Error).message;
      }
    },
    //send the hint request to the backend
    async HintReq(action: string){
      if (this.board && !this.board.status.isLost && !this.board.status.isWon && (action === 'reveal' || action === 'flag')){
        //send the hint request to the backend  
        this.board = await hint(action);
        this.add15Seconds();

        //check if the game is over
        if(this.board?.status.isLost || this.board?.status.isWon){
          clearInterval(this.timer!);
          if(this.board.status.isWon){
            this.actualizeLeaderboard();
          }
        }
      }
    },
    //open or close the chat
    openCloseChat(){
      this.isChatOpen = !this.isChatOpen;
    },
    //send the chat message to the backend
    async sendChatMsg(){
      if(this.newMsg.trim() !== ""){
        try{
          await sendChatMsg(this.newMsg);
          this.newMsg = "";
          this.chat = await getChatMsgs();
        }
        catch (err) {
          this.error = (err as Error).message;
        }
      }
    }
  },
  //generate the game board and start the timer at the beginning
  async mounted() {
    try {
      //generate new game board;
      changeDifficulty(this.difficulty).then((newBoard) => {
        this.board = newBoard;
      });
      this.initTimer();
      this.chat = await getChatMsgs();
    }
    catch (err) {
      this.error = (err as Error).message;
    }
  }
});
</script>
  
<!--CSS styles for GameView-->
<style scoped>
  .title_container{
    margin: 0;
  }
  .title{
    color: white;
    text-shadow: 1px 1px 5px black;
    overflow-wrap: anywhere;
  }

  #menu_btn{
    position: absolute;
    top: 20px;
    left: 20px;
    padding: 10px 15px;
    box-shadow: 5px 5px 2px rgba(255, 255, 255, 0.209);
  }
  #reset_btn{
    position: absolute;
    top: 20px;
    right: 20px;
    padding: 10px 15px;
    box-shadow: 5px 5px 2px rgba(255, 255, 255, 0.209);
  }
  .img_btn{
    margin-left: 8px;
  }
  .game_board {
    display: grid;
    gap: 3px;
    justify-content: center;
  }
  #board{
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
  }
  .board_row {
    display: flex;
    gap: 3px;
  }

  /* styles for a board cells */
  .board_cell {
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    border-radius: 4px;
    box-shadow: inset 4px 3px 2px rgb(115, 153, 176);
    background-color: #7CD3E7;
    font-family:'Inter';
  }
  .board_cell:hover {
    background-color: #6AB9D4;
  }
  .board_cell.revealed {
    background-color: #0A0B20;
    box-shadow: inset 3px 3px 2px rgb(0, 0, 0);
    box-shadow: 0px 0px 1px white;
    cursor: default;
  }
  .board_cell.flagged::after {
    content: "🚩";
    font-size: 18px;
  }
  .board_cell.isMine::after {
    content: "💣";
    font-size: 18px;
  }
  .board_cell.isMine{
    background-color: #FF7373;  
  }
  .board_cell.nullCell{
    box-shadow: inset 0px 0px 0px rgb(0, 0, 0);
    content: "";
  }

  /* styles for showing the stats at the bottom of a page */
  #bottom_info{
    display: flex;
    margin-top: 20px;
    gap: 5%;
    justify-content: center;
  }
  .stats{
    color: black;
    background-color: white;
    padding: 10px 15px;
    border-radius: 15px;
    box-shadow: inset 5px 5px 2px rgb(167, 167, 167);
    display: flex;
  }
  #diff_select{
    margin-left: 4px;
    padding: 2px;
    border-radius: 7px;
    border: 0px;
    box-shadow: 1px 1px 3px rgb(54, 54, 54);
  }

  /* Styles for the status info at the end of the game */
  .status_text{
    font-size: 3em;
    color: white;
    text-shadow: 1px 1px 5px black;
    margin-top: 20px;
    overflow-wrap: anywhere;
    width: 40px;
    padding: 0px 20px;
  }

  /* styles for the hints */
  #hints{
    display: flex;
    justify-content: center;
  } 
  .hint{
    position: relative;
  }
  #eye_hint, #flag_hint{
    color: white;
    background-color: rgb(255, 255, 255, 0.05);
    box-shadow: 0px 0px 2px rgba(255, 255, 255, 0.5);
  }
  #eye_hint_text{
    width: 30vw;
    display: none;
    position: absolute;
    background-color: black;
    color: white;
    padding: 4px;
    border-radius: 2px;
    box-shadow: 2px 2px 2px rgba(20, 20, 20, 0.209);
  }
  #flag_hint_text{
    width: 30vw;
    display: none;
    position: absolute;
    background-color: black;
    color: white;
    padding: 4px;
    border-radius: 2px;
    box-shadow: 2px 2px 2px rgba(20, 20, 20, 0.209);
  }
  .hint:hover #eye_hint_text{
    display: block;
  }
  .hint:hover #flag_hint_text{
    display: block;
  }

  /* styles for the chat */
  #chat_btn_div{
    position: relative;
  }
  #chat_btn{
    position: fixed;
    bottom: 20px;
    right: 20px;
    padding: 10px 15px;
    box-shadow: 0px 0px 2px rgba(255, 255, 255, 0.5);
    color: white;
    background-color: rgb(255, 255, 255, 0.05);
  }
  #chat_div{
    align-content: space-between;
    background-color: black;
    position: fixed;
    top: 0px;
    right: 0px;
    height: 100vh;
    padding: 0px 15px;
    border-left: 1px solid white;
    box-shadow: -10px 0px 5px rgba(0, 0, 0, 0.4);
    font-size: medium;
    text-align: left;
  }
  .close_btn{
    position: absolute;
    background-color: black;
    color: white;
    top: 0px;
    right: 5px;
    padding: 5px 10px;
    font-size: medium;
    box-shadow: 0px 0px 2px rgba(255, 255, 255);
  }
  #chat_text{ 
    overflow-y: scroll;
    scrollbar-color: white #0A0B20;
  }
  #chat_input{
    display: flex;
    justify-content: center;
    align-items: center;
  }
  #chat_input_text{
    width: 70%;
    padding: 8px;
    border-radius: 15px;
    border: 0px;
    box-shadow: 0px 0px 2px rgba(255, 255, 255);
    background-color: black;
    color: white;
  }
  #chat_send_btn{
    background-color: black;
    color: white;
    padding: 5px 10px;
    font-size: medium;
    box-shadow: 0px 0px 2px rgba(255, 255, 255);
  }
</style>

// frontend/svelte/src/routes/game.svelte
<!-- 
    File: game.svelte
    Author: Dominik Šmíd
    Date: 11.12.2024
    Description: 
        This file implements the main game interface using the Svelte framework. 
        It includes the game chat functionality, allowing players to send and 
        receive messages in real time, as well as other game-related UI components.
-->

<script>
    import { onMount } from 'svelte';
    import { tick } from "svelte";
    import { getUser } from "../services/getUser";
    import { generateBoard } from "../services/generateBoard";
    import { flagCell } from "../services/flagCell";
    import { revealCell } from "../services/revealCell";
    import { changeDifficulty } from "../services/changeDifficulty";
    import { sendTime } from "../services/sendTime";
    import { saveTime } from "../services/saveTime";
    import { getChat } from "../services/getChat"
    import { sendMessage } from "../services/sendMessage";
    import { each } from 'svelte/internal';
    
    let data;
    let chat;
    let gameboard;
    let nickname;
    let mines = 0;
    let numofflags = mines;
    let interval;
    let seconds = 0;

    let Easyoption = false;
    let Mediumoption = false;
    let Hardoption = false;

    let gameWon = false;
    let gameLost = false;

    let showChat = false;
    let message;
    let chatInterval = 1000;


    let getdata = async() => {
        try {
            chat = await getChat();
            nickname = await getUser();
            data = await generateBoard();
            gameboard = data.board;
            if (data.lastTime) {
                seconds = data.lastTime;
            }
            mines = gameboard.details.mines;
            // set correct number of mines
            numofflags = (mines - getmines(gameboard));
            // get difficulty
            if (gameboard.difficulty == "easy") {
                Easyoption = true;
                Mediumoption = false;
                Hardoption = false;
            }
            else if (gameboard.difficulty == "medium") {
                Easyoption = false;
                Mediumoption = true;
                Hardoption = false;
            }
            else {
                Easyoption = false;
                Mediumoption = false;
                Hardoption = true;
            }
            // manage start of time
            if (gameboard.status.isLost || gameboard.status.isWon) {
                handleTime(false);
            }
            else if (gameboard.status.isStarted) {
                handleTime(true);
            }
            // manage you won/lost text
            if (gameboard.status.isWon) {
                gameWon = true;
            }
            else if (gameboard.status.isLost) {
                gameLost = true
            }
        } catch (error) {
            console.error("Error fetching data:", error);
        }
    }
    
    onMount(() => {
        if (showChat) {
            scrollToBottom();
        }
        document.body.classList.add('dark-bg');
        getdata();
        return () => {
            console.log("saving time");
            saveTime(seconds);
        };
    });

    let getmines = (board) => {
        const rows = board.details.rows;
        const cols = board.details.cols;
        let count = 0;
        for (let i = 0; i < rows; i++) {
            for (let j = 0; j < cols; j++) {
                if (board.board[i][j].isFlagged) {count++;}
            }
        }
        return count;
    }

    let handleTime = (started) => {
        if (started) {
            interval = setInterval(() => {
                seconds++;
            }, 1000);
        }
        else {
            seconds = 0;
            clearInterval(interval);
        }
    }

    let handleLeftClick = async(row, col) => {
        if (!gameboard.status.isStarted) {
            handleTime(true);
        }
        try {
            gameboard = await revealCell(row, col, gameboard);
            if (gameboard.status.isWon) {
                sendTime(seconds, gameboard.difficulty);
            }
        }
        catch {}
        if (gameboard.status.isLost || gameboard.status.isWon) {
            if (gameboard.status.isLost) {
                gameLost = true
            }
            else if (gameboard.status.isWon) {
                gameWon = true;
            }
            else {
                gameLost = false;
                gameWon = false;
            }
            clearInterval(interval);
        }
    };

    let handleRightClick = async(event, row, col) => {
        if (event) {
            event.preventDefault();
        }

        try {
            gameboard = await flagCell(row, col, gameboard);
            if (gameboard.board[row][col].isFlagged) {
                decrement(gameboard.status);
            }
            else {
                increment(gameboard.status);
            }
        } catch {}
    };

    let resetboard = async() => {
        try {
            gameboard = await changeDifficulty(gameboard.difficulty);
            mines = gameboard.details.mines;
            numofflags = mines;
            handleTime(false);
        } catch {}
        gameLost = false;
        gameWon = false;
    }

    let difficultyChange = async(option) => {
        try {
            gameboard = await changeDifficulty(option)
            mines = gameboard.details.mines;
            numofflags = mines;
            handleTime(false);
        } catch {}
        gameLost = false;
        gameWon = false;
    }

    let increment = (state) => {
        if (!state.isWon && !state.isLost) {
            numofflags += 1;
        }
    }

    let decrement = (state) => {
        if (!state.isWon && !state.isLost) {
            numofflags -= 1;
        }
    }

    let handleHintEye = async () => {
        for (let r = 0; r < gameboard.details.rows; r++) {
            for (let c = 0; c < gameboard.details.cols; c++) {
                if ((!gameboard.board[r][c].isRevealed) && gameboard.board[r][c].value >= 0) {
                    await handleLeftClick(r, c);
                    seconds += 15;
                    return;
                }
            }
        }
    }

    let handleHintFlag = async() => {
        for (let r = 0; r < gameboard.details.rows; r++) {
            for (let c = 0; c < gameboard.details.cols; c++) {
                if (gameboard.board[r][c].value == -1 && !gameboard.board[r][c].isFlagged) {
                    try {
                        await handleRightClick(null, r, c);
                        seconds += 15;
                        return;
                    }
                    catch (error){
                        console.log(error);
                    }
                }
            }
        }
    }

    let handleEscape = (event) => {
        if (event.key == "Escape") {
            toggleChat();
        }
    };


    let toggleChat = async() => {
        showChat = !showChat;
        await updateChat();
        scrollToBottom();
    }

    let updateChat = async() => {
        if (showChat) {
            chatInterval = setInterval(async() => {
                chat = await getChat();
            }, 1000);
        }
        else {
            clearInterval(chatInterval);
        }
    }

    let handleSubmit = async () => {
        if (message == "") {
            return;
        }
        await sendMessage(message);
        chat = await getChat();
        message = "";

        await tick();
        scrollToBottom();
    }

    let handleEnter = (event) => {
        if (event.key === "Enter") {
            handleSubmit(message);
        }
    }

    let scrollToBottom = () => {
        const chatbox = document.querySelector('.chatbox');
        if (chatbox) {
            chatbox.scrollTop = chatbox.scrollHeight;
        }
    }

</script>

{#if showChat}
    <div class="backdrop" on:click|self={toggleChat} on:keydown={handleEscape}>
        <div class="chatcontainer" on:keydown={handleEscape}>
            <div class="chatheader">
                <div class="greet">Welcome to the game chat!</div>
                <button class="x-btn" on:click={toggleChat}>X</button>
            </div>
            <div class="chatbox">
                {#each chat as messages}
                    <div class="name">{messages.sender}:</div>
                    <div class="message">{messages.content}</div>
                    <div class="date">{new Date(messages.timestamp.seconds * 1000).toUTCString()}</div>
                    <br>
                {/each}
            </div>
            <div class="chatfooter">
                <input class="messageinput" type="text" placeholder="message" bind:value={message} on:keydown={handleEnter}>
                <button class="send-btn" on:click={handleSubmit}>send</button>
            </div>
        </div>
    </div>
{/if}


<main>
    <div class="container">
        <div class="header">
            <a href="#/"><button class="Menu-button">Menu</button></a>
            <h1 class="headline">MINESWEEPER</h1>
            <button class="Reset-button" on:click={resetboard}>Reset</button>
        </div>
        <!-- <div class="headline">{nickname}</div> -->
        <div class="board">
            {#if gameWon || gameLost}
                <div class="sidelabel">Y<br>O<br>U</div>                
            {/if}
            <div class="grid">
                {#if gameboard}
                    {#each gameboard.board as row, rowIndex}
                    <div class="row">
                        {#each row as cell, colIndex}
                            <!-- bomb -->
                            {#if cell.value == -1}
                                {#if cell.isFlagged}
                                    <button
                                        class={gameboard.difficulty == 'hard' ? "lightcellsmall" : "lightcellbig"}
                                        on:contextmenu={(event) => handleRightClick(event, rowIndex, colIndex)}
                                    >🚩</button>
                                {:else if cell.isRevealed}
                                    <button class={gameboard.difficulty == 'hard' ? "redcellsmall" : "redcellbig"}>💣</button>
                                {:else}
                                    {#if gameboard.status.isLost}
                                        <button class={gameboard.difficulty == 'hard' ? "lightcellsmall" : "lightcellbig"}>💣</button>
                                    {:else}
                                    <button
                                        class={gameboard.difficulty == 'hard' ? "lightcellsmall" : "lightcellbig"}
                                        aria-label="emptycell"
                                        on:click={() => handleLeftClick(rowIndex, colIndex)}
                                        on:contextmenu={(event) => handleRightClick(event, rowIndex, colIndex)}
                                    ></button>
                                    {/if}
                                {/if}
                            <!-- number -->
                            {:else}
                                {#if cell.isFlagged}
                                    {#if gameboard.status.isLost}
                                        <button class={gameboard.difficulty == 'hard' ? "redcellsmall" : "redcellbig"}>🚩</button>
                                    {:else}
                                        <button
                                            class={gameboard.difficulty == 'hard' ? "lightcellsmall" : "lightcellbig"}
                                            on:contextmenu={(event) => handleRightClick(event, rowIndex, colIndex)}
                                        >🚩</button>
                                    {/if}
                                {:else if cell.isRevealed}
                                    {#if cell.value == 0}
                                        <button class={gameboard.difficulty == 'hard' ? "zerodarksmall" : "zerodarkbig"} aria-label="emptycell"></button>
                                    {:else}
                                        <button class={gameboard.difficulty == 'hard' ? "darkcellsmall" : "darkcellbig"}>{cell.value}</button>
                                    {/if}
                                {:else}
                                    <button
                                        class={gameboard.difficulty == 'hard' ? "lightcellsmall" : "lightcellbig"}
                                        aria-label="emptycell"
                                        on:click={() => handleLeftClick(rowIndex, colIndex)}
                                        on:contextmenu={(event) => handleRightClick(event, rowIndex, colIndex)}
                                    ></button>
                                {/if}
                            {/if}
                        {/each}
                    </div>
                    {/each}
                {:else}
                    <div class="nick">loading gameboard</div>
                {/if}
            </div>
            {#if gameWon}
                <div class="sidelabel">W<br>O<br>N</div>                
            {:else if gameLost}
                <div class="sidelabel">L<br>O<br>S<br>T</div>
            {/if}
        </div>

        <div class="hints">
            <button class="hint-btn" on:click={handleHintEye}><img class="eye" src="img/eye.png" alt="eye icon"></button>
            <button class="hint-btn" on:click={handleHintFlag}><img class="hintflag" src="img/hintflag.png" alt="hint flag"></button>
        </div>

        <div class="footer">
            <button class="Time">Time: {Math.floor(seconds / 60)}:{seconds % 60 < 10 ? "0"+ seconds%60 : seconds%60}</button>
            <button class="MinesLeft">Mines left: {numofflags}/{mines}</button>
            <select>
                <option on:click={() => difficultyChange("easy")} value="easy" selected={Easyoption}>Easy</option>
                <option on:click={() => difficultyChange("medium")} value="medium" selected={Mediumoption}>Medium</option>
                <option on:click={() => difficultyChange("hard")} value="hard" selected={Hardoption}>Hard</option>
            </select>
        </div>
    </div>
    <button class="chat-btn" on:click={toggleChat}>Open Chat</button>
</main>

<style>
    /* CHAT */
    .chat-btn {
        position: fixed;
        bottom: 20px;
        right: 20px;
        font-size: 1.2rem;
        height: fit-content;
    }

    .backdrop {
        width: 100%;
        height: 100%;
        position: fixed;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1;
        display: flex;
        justify-content: flex-end;
    }

    .chatcontainer {
        width: 500px;
        min-width: 20%;
        height: 100%;
        background-color: rgba(10, 10, 10, 0.8);
        color: white;
        border-left: 2px solid white;
        display: flex;
        flex-direction: column;
    }

    .chatbox {
        flex: 1;
        overflow-y: auto;
        margin-bottom: 80px;
        padding: 0 15px;
    }

    .chatheader {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
        border-bottom: 2px solid white;
        padding: 15px 15px;
        background-color: black;
    }

    .chatfooter {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: black;
        border-top: 2px solid white;
        padding: 15px 15px;
    }

    .greet {
        font-size: 1.7rem;
    }

    .x-btn {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 1rem;
        padding: 5px;
        width: 30px;
        height: 30px;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin: 0;
        right: 20px;
        top: 20px;
        position: absolute;
    }

    .name {
        font-size: 1.3rem;
        font-weight: bold;
    }

    .message {
        font-size: 1rem;
    }

    .date {
        font-size: 0.8rem;
        display: flex;
        justify-content: end;
        margin: 0 10px 10px 0;
    }

    .messageinput {
        width: 20%;
    }

    .send-btn {
        font-size: 1.2rem;
        border-radius: 8px;
        margin: 0 0 0 10px;
    }

    /* HINTS */
    .hint-btn {
        font-size: 0;
        margin: 0;
        padding: 0;
        background-color: #0A0B20;
        border: none;
    }

    .hint-btn:active {
        background-color:#0A0B20;
    }
    
    .hints {
        display: flex;
        justify-content: center;
        gap: 100px;
        margin: 1rem 0;
    }

    .eye {
        color: white;
        height: 40px;
        cursor: pointer;
    }

    .hintflag {
        filter: brightness(0) invert(1);
        width: 40px;
        cursor: pointer;
    }

    .footer {
        display: flex;
        justify-content: center;
        gap: 5rem;
        margin: 0;
    }

    select {
        font-size: 2rem;
        border-radius: 10pt;
        margin: 1rem;
        cursor: pointer;
        text-align: center;
    }

    option {
        font-size: 25px;
        font-weight: bold;
        cursor: pointer;
        color: black;
    }

    main {
        display: flex;
        justify-content: center;
        height: 100%;
        position: relative;
        overflow: scroll;
    }

    .container {
        display: flex;
        flex-direction: column;
    }

    .board {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin: auto;
        position: relative;
    }

    .grid {
        display: flex;
        flex-direction: column;
    }

    .sidelabel {
        margin: 0 5rem;
        font-size: 5rem;
        font-weight: bold;
        color: white;
        text-align: center;
        display: flex;
        align-self: center;
    }

    .row {
        display: flex;
    }

    /* BIG CELLS */
    .redcellbig {
        font-size: 1.5rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #FF7373;
        border: none;
        width: 3rem;
        height: 3rem;
        margin: 1px;
        border-radius: 5px;
        box-shadow: inset 6px 6px 2px rgba(0, 0, 0, 0.2)
    }

    .lightcellbig {
        font-size: 1.5rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #7CD3E7;
        border-color: #0A0B20;
        width: 3rem;
        height: 3rem;
        margin: 1px;
        border-radius: 5px;
        box-shadow: inset 6px 6px 2px rgba(0, 0, 0, 0.2)
    }

    .zerodarkbig {
        background-color: #0A0B20;
        width: 3rem;
        height: 3rem;
        margin: 1px;
        border: solid 4px black;
        border-radius: 5px;
    }

    .darkcellbig {
        font-size: 1.5rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #0A0B20;
        border-color: white;
        color: white;
        width: 3rem;
        height: 3rem;
        margin: 1px;
        border-radius: 5px;
        box-shadow: inset -6px -6px 3px rgba(255, 255, 255, 0.4)
    }

    /* SMALL CELLS */
    .redcellsmall {
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #FF7373;
        border: none;
        width: 2rem;
        height: 2rem;
        margin: 0px;
        border-radius: 5px;
        box-shadow: inset 4px 4px 2px rgba(0, 0, 0, 0.2)
    }

    .lightcellsmall {
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #7CD3E7;
        border-color: #0A0B20;
        width: 2rem;
        height: 2rem;
        margin: 0px;
        border-radius: 5px;
        box-shadow: inset 4px 4px 2px rgba(0, 0, 0, 0.2)
    }

    .zerodarksmall {
        background-color: #0A0B20;
        width: 2rem;
        height: 2rem;
        margin: 0px;
        border-color: black;
        border-radius: 5px;
    }

    .darkcellsmall {
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #0A0B20;
        border-color: white;
        color: white;
        width: 2rem;
        height: 2rem;
        margin: 0px;
        border-radius: 5px;
        box-shadow: inset -4px -4px 3px rgba(255, 255, 255, 0.4)
    }

    .Menu-button {
    position: absolute;
    top: 5%;
    left: 5%;
    }

    .Reset-button {
    position: absolute;
    top: 5%;
    right: 5%;
    }

    .headline {
    color: white;
    font-size: 4rem;
    text-align: center;
    }

    .nick {
        color: white;
        font-size: 3rem;
    }

    /* width < 900 */
    @media (max-width: 900px) {
        .container {
            align-self: center;
        }
        
        .headline {
            font-size: 2rem;
        }

        .Reset-button {
            font-size: 1.2rem;
            top: 0.5rem;
            right: 0.5rem;
        }

        .Menu-button {
            font-size: 1.2rem;
            top: 0.5rem;
            left: 0.5rem;
        }

        .board {
            margin-top: 1rem;
            margin-bottom: 1rem;
        }

        /* BIG CELLS */
        .redcellbig {
            font-size: 1rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #FF7373;
            border: none;
            width: 1.5rem;
            height: 1.5rem;
            margin: 0px;
            border-radius: 5px;
        }

        .lightcellbig {
            font-size: 1rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #7CD3E7;
            border-color: #0A0B20;
            width: 1.5rem;
            height: 1.5rem;
            margin: 0px;
            border-radius: 5px;
        }

        .zerodarkbig {
            font-size: 1rem;
            background-color: #0A0B20;
            width: 1.5rem;
            height: 1.5rem;
            margin: 0px;
            border: none;
            border-radius: 5px;
        }

        .darkcellbig {
            font-size: 1rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #0A0B20;
            width: 1.5rem;
            height: 1.5rem;
            margin: 0px;
        }

        /* SMALL CELLS */
        .redcellsmall {
            font-size: 0.7rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #FF7373;
            border: none;
            width: 1.2rem;
            height: 1.2rem;
            margin: 0px;
            border-radius: 5px;
            box-shadow: inset 4px 4px 2px rgba(0, 0, 0, 0.2)
        }

        .lightcellsmall {
            font-size: 0.7rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #7CD3E7;
            border-color: #0A0B20;
            width: 1.2rem;
            height: 1.2rem;
            margin: 0px;
            border-radius: 5px;
            box-shadow: inset 4px 4px 2px rgba(0, 0, 0, 0.2)
        }

        .zerodarksmall {
            font-size: 0px;
            background-color: #0A0B20;
            width: 1.2rem;
            height: 1.2rem;
            margin: 0px;
            border: solid 0px black;
            border-radius: 5px;
        }

        .darkcellsmall {
            font-size: 1rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            background-color: #0A0B20;
            border-color: white;
            color: white;
            width: 1.2rem;
            height: 1.2rem;
            margin: 0px;
            border-radius: 5px;
            box-shadow: inset -4px -4px 3px rgba(255, 255, 255, 0.4)
        }

        .sidelabel{
            margin: 1rem;
            font-size: 3rem;
            font-weight: bold;
            color: white;
            text-align: center;
            display: flex;
            align-self: center;
        }

        .Time, .MinesLeft, select, option {
            font-size: 1.2rem;
            margin: 0px;
        }

        .footer {
            gap: 1rem;
        }
    }  
</style>
